# Generated by Django 4.2.16 on 2024-12-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='media/posts/syra.jpg', upload_to='articles/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
