# Generated by Django 4.2.16 on 2024-12-11 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_relevant_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='relevant_quote',
        ),
    ]
