# Generated by Django 4.2.16 on 2024-12-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_delete_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_breaking',
            field=models.BooleanField(default=False),
        ),
    ]
