# Generated by Django 4.2.16 on 2024-12-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='homepage',
            field=models.BooleanField(default=False),
        ),
    ]
