# Generated by Django 4.2.16 on 2024-12-12 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0004_initial'),
        ('articles', '0008_journalist_alter_article_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contributors.journalist'),
        ),
        migrations.DeleteModel(
            name='Journalist',
        ),
    ]
