# Generated by Django 4.2.16 on 2024-12-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalist',
            name='first_name',
            field=models.TextField(default='Michael'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journalist',
            name='last_name',
            field=models.TextField(default='McCourt'),
            preserve_default=False,
        ),
    ]
